### ISSUE TITLE
[Bitburner Help Bot.py]Command suggestions

### ISSUE THREAD

**Issue by tyrope** [Mendenj85/Bitburner-Scripts-by-Deaeth85#10]
* !pr, !source and/or !repo to link here.
* !ns alias to !md (since it's quite a habit to type `ns.func`, therefore `!ns func` feels more natural than `!md func`

**Comment by Mendenj85** [comment]
Added !source

Unsure on changing md to ns, md stands for markdown since it pulls any and every markdown page - will get more opinions before deciding

**Comment by Mendenj85** [comment]
Added !ns, does same thing as !md, so now two methods for those who might prefer either way
